import { ROLES } from '../config/roles';

export const DEFAULT_OFFICERS = {
  [ROLES.TALATHI]: {
    id: 'GOV-002',
    name: 'Prakash Shinde',
    localName: 'प्रकाश शिंदे',
    role: 'TALATHI',
    department: 'DEPT-REV',
    designation: 'Talathi (Circle Wagholi)',
    jurisdiction: 'Wagholi Circle, Haveli Tehsil, Pune',
    villageCode: 'VIL-WAG',
    tehsilCode: 'TEH-HAV',
    districtCode: 'DIST-PUN',
    stateCode: 'MH',
    office: 'Talathi Office, Wagholi Circle',
    email: 'prakash.shinde@maharashtra.gov.in',
  },
  [ROLES.TEHSILDAR]: {
    id: 'GOV-001',
    name: 'Sanjay Deshmukh',
    localName: 'संजय देशमुख',
    role: 'TEHSILDAR',
    department: 'DEPT-REV',
    designation: 'Tehsildar & Executive Magistrate',
    jurisdiction: 'Haveli Taluka, Pune District',
    tehsilCode: 'TEH-HAV',
    districtCode: 'DIST-PUN',
    stateCode: 'MH',
    office: 'Tehsildar Office, Haveli, Pune',
    email: 'sanjay.deshmukh@maharashtra.gov.in',
  },
  [ROLES.SRO]: {
    id: 'GOV-003',
    name: 'Rekha Joshi',
    localName: 'रेखा जोशी',
    role: 'SRO',
    department: 'DEPT-REG',
    designation: 'Sub-Registrar of Assurances (Class I)',
    jurisdiction: 'Sub-Registrar Office Haveli No 5, Pune',
    tehsilCode: 'TEH-HAV',
    districtCode: 'DIST-PUN',
    stateCode: 'MH',
    office: 'Sub-Registrar Office Haveli No 5',
    email: 'rekha.joshi@igrmaharashtra.gov.in',
  },
  [ROLES.COLLECTOR]: {
    id: 'GOV-004',
    name: 'Dr. Suhas Diwase, IAS',
    localName: 'डॉ. सुहास दिवसे',
    role: 'COLLECTOR',
    department: 'DEPT-DIST',
    designation: 'District Collector & District Magistrate',
    jurisdiction: 'Pune District (14 Tehsils)',
    districtCode: 'DIST-PUN',
    stateCode: 'MH',
    office: 'Collectorate Office, Pune',
    email: 'collector.pune@maharashtra.gov.in',
  },
  [ROLES.STATE_PMU]: {
    id: 'GOV-011',
    name: 'Anil Verma',
    localName: 'अनिल वर्मा',
    role: 'STATE_PMU',
    department: 'DEPT-STATE',
    designation: 'State PMU Head — Maharashtra DILRMP',
    jurisdiction: 'State of Maharashtra (36 Districts)',
    stateCode: 'MH',
    office: 'Settlement Commissionerate & Land Records, Pune',
    email: 'anil.verma@pmu.landrecords.gov.in',
  },
  [ROLES.NATIONAL_MONITOR]: {
    id: 'GOV-013',
    name: 'Meera Sengupta',
    localName: 'मीरा सेनगुप्ता',
    role: 'NATIONAL_MONITOR',
    department: 'DEPT-NAT',
    designation: 'National Cadastral Monitoring Officer',
    jurisdiction: 'National (36 States & Union Territories)',
    office: 'Department of Land Resources (DoLR), New Delhi',
    email: 'meera.sengupta@dolr.gov.in',
  },
  [ROLES.ADMIN]: {
    id: 'GOV-014',
    name: 'Manoj Tiwari',
    localName: 'मनोज तिवारी',
    role: 'ADMIN',
    department: 'DEPT-ADMIN',
    designation: 'Land Stack System & Security Administrator',
    jurisdiction: 'Platform-wide / National NIC Cloud',
    office: 'NIC Land Records Division, New Delhi',
    email: 'admin.landstack@nic.in',
  },
};

export const DEFAULT_CITIZENS = [
  {
    id: 'CIT-001',
    name: 'Aarav Patil',
    localName: 'आरव पाटील',
    stateCode: 'MH',
    mobile: '+91 98230 45891',
    email: 'aarav.patil@example.com',
    aadhaarHash: 'XXXX-XXXX-8912',
    address: 'Gat No 42, Wagholi, Pune, Maharashtra 412207',
  },
  {
    id: 'CIT-002',
    name: 'Sunita Kulkarni',
    localName: 'सुनिता कुलकर्णी',
    stateCode: 'MH',
    mobile: '+91 98231 12345',
    email: 'sunita.k@example.com',
    aadhaarHash: 'XXXX-XXXX-4519',
    address: 'Flat 402, Shivneri Apts, Lohegaon, Pune 411047',
  },
  {
    id: 'CIT-003',
    name: 'Rajesh Gaikwad',
    localName: 'राजेश गायकवाड',
    stateCode: 'MH',
    mobile: '+91 98232 23456',
    email: 'rajesh.g@example.com',
    aadhaarHash: 'XXXX-XXXX-7821',
    address: 'Survey 118, Hinjawadi Phase 1, Pune 411057',
  },
  {
    id: 'CIT-004',
    name: 'Priya Shinde',
    localName: 'प्रिया शिंदे',
    stateCode: 'MH',
    mobile: '+91 98233 34567',
    email: 'priya.shinde@example.com',
    aadhaarHash: 'XXXX-XXXX-3342',
    address: 'Gat 88, Manjri Khurd, Haveli, Pune 412307',
  },
  {
    id: 'CIT-005',
    name: 'Rameshwar Chaudhary',
    localName: 'रामेश्वर चौधरी',
    stateCode: 'RJ',
    mobile: '+91 98290 12345',
    email: 'rameshwar.c@example.com',
    aadhaarHash: 'XXXX-XXXX-1122',
    address: 'Khasra 210, Jhotwara, Jaipur, Rajasthan 302012',
  },
];
