export const DEFAULT_OFFICERS = {
  TALATHI: {
    id: 'TEST_GOV_002',
    role: 'TALATHI',
    name: 'Sayali Wadhai',
    localName: 'सायली वाढई',
    email: 'sayali.wadhai@maharashtra.gov.in',
    designation: 'Talathi (Circle Wagholi)',
    context: { district: 'Pune', tehsil: 'Haveli', villages: ['Wagholi'] },
  },
  TALATHI_PRAKASH: {
    id: 'GOV-002',
    role: 'TALATHI',
    name: 'Prakash Shinde',
    localName: 'प्रकाश शिंदे',
    email: 'prakash.shinde@maharashtra.gov.in',
    designation: 'Village Revenue Officer (Wagholi)',
    context: { district: 'Pune', tehsil: 'Haveli', villages: ['Wagholi'] },
  },
  TEHSILDAR: {
    id: 'TEST_GOV_001',
    role: 'TEHSILDAR',
    name: 'Sanjay Deshmukh',
    localName: 'संजय देशमुख',
    email: 'sanjay.deshmukh@maharashtra.gov.in',
    designation: 'Tehsildar & Executive Magistrate',
    context: { district: 'Pune', tehsil: 'Haveli' },
  },
  SRO: {
    id: 'TEST_GOV_003',
    role: 'SRO',
    name: 'Rekha Joshi',
    localName: 'रेखा जोशी',
    email: 'rekha.joshi@igrmaharashtra.gov.in',
    designation: 'Sub-Registrar Class-1 Haveli',
    context: { district: 'Pune', sroCode: 'SRO-HAVELI-5' },
  },
  COLLECTOR: {
    id: 'TEST_GOV_004',
    role: 'COLLECTOR',
    name: 'Dr. Suhas Diwase',
    localName: 'डॉ. सुहास दिवसे',
    email: 'collector.pune@maharashtra.gov.in',
    designation: 'District Collector & DM',
    context: { district: 'Pune' },
  },
  DISTRICT_COLLECTOR: {
    id: 'TEST_GOV_004',
    role: 'COLLECTOR',
    name: 'Dr. Suhas Diwase',
    localName: 'डॉ. सुहास दिवसे',
    email: 'collector.pune@maharashtra.gov.in',
    designation: 'District Collector & DM',
    context: { district: 'Pune' },
  },
  ULB_OFFICER: {
    id: 'GOV-006',
    role: 'ULB_OFFICER',
    name: 'Anita Bhosale',
    localName: 'अनिता भोसले',
    email: 'anita.bhosale@pmc.gov.in',
    designation: 'Urban Land Records Officer',
    context: { district: 'Pune', municipality: 'PMC' },
  },
  SURVEY_GIS: {
    id: 'GOV-005',
    role: 'SURVEY_GIS',
    name: 'Vikram Patole',
    localName: 'विक्रम पाटोळे',
    email: 'vikram.patole@maharashtra.gov.in',
    designation: 'Cadastral Survey Specialist',
    context: { district: 'Pune', tehsil: 'Haveli' },
  },
  STATE_PMU: {
    id: 'TEST_GOV_011',
    role: 'STATE_PMU',
    name: 'Anil Verma',
    localName: 'अनिल वर्मा',
    email: 'anil.verma@pmu.landrecords.gov.in',
    designation: 'State PMU Project Lead',
    context: { state: 'MH' },
  },
  NATIONAL_MONITOR: {
    id: 'TEST_GOV_013',
    role: 'NATIONAL_MONITOR',
    name: 'Meera Sengupta',
    localName: 'मीरा सेनगुप्ता',
    email: 'meera.sengupta@dolr.gov.in',
    designation: 'National MIS Lead',
    context: { level: 'National' },
  },
  NATIONAL_ADMIN: {
    id: 'TEST_GOV_013',
    role: 'NATIONAL_MONITOR',
    name: 'Meera Sengupta',
    localName: 'मीरा सेनगुप्ता',
    email: 'meera.sengupta@dolr.gov.in',
    designation: 'National MIS Lead',
    context: { level: 'National' },
  },
  ADMIN: {
    id: 'TEST_GOV_014',
    role: 'ADMIN',
    name: 'Manoj Tiwari',
    localName: 'मनोज तिवारी',
    email: 'admin.landstack@nic.in',
    designation: 'Platform Administrator',
    context: { access: 'Global' },
  },
  SYSTEM_ADMIN: {
    id: 'TEST_GOV_014',
    role: 'ADMIN',
    name: 'Manoj Tiwari',
    localName: 'मनोज तिवारी',
    email: 'admin.landstack@nic.in',
    designation: 'Platform Administrator',
    context: { access: 'Global' },
  },
};

export const DEFAULT_CITIZENS = [
  {
    id: 'TEST_CIT_001',
    name: 'Abhishek Gujar',
    localName: 'अभिषेक गुजर',
    mobile: '+91 98230 45891',
    email: 'abhishek.gujar@example.com',
    stateCode: 'MH',
    aadhaarHash: 'XXXX-XXXX-8912',
    address: 'Gat No 42, Wagholi, Pune, Maharashtra 412207',
  },
  {
    id: 'TEST_CIT_002',
    name: 'Ankush Vishwakarma',
    localName: 'अंकुश विश्वकर्मा',
    mobile: '+91 98231 12345',
    email: 'ankush.vishwakarma@example.com',
    stateCode: 'MH',
    aadhaarHash: 'XXXX-XXXX-4519',
    address: 'Flat 402, Wagholi Hills, Haveli, Pune 412207',
  },
  {
    id: 'TEST_CIT_003',
    name: 'Priyanshu Manke',
    localName: 'प्रियांशू मानके',
    mobile: '+91 98232 23456',
    email: 'priyanshu.manke@example.com',
    stateCode: 'MH',
    aadhaarHash: 'XXXX-XXXX-7821',
    address: 'Plot 18, Ubale Nagar, Wagholi, Pune 412207',
  },
];
