import { ROLES } from './roles';

/**
 * Fine-grained permissions matrix for Land Stack operations
 */
export const PERMISSIONS = {
  VIEW_PUBLIC_RECORDS: 'VIEW_PUBLIC_RECORDS',
  DOWNLOAD_DIGITAL_712: 'DOWNLOAD_DIGITAL_712',
  APPLY_MUTATION: 'APPLY_MUTATION',
  VIEW_CITIZEN_PARCELS: 'VIEW_CITIZEN_PARCELS',
  VIEW_WATCHLIST: 'VIEW_WATCHLIST',
  LODGE_GRIEVANCE: 'LODGE_GRIEVANCE',

  // Revenue Officer Permissions
  ENTER_PENCIL_ENTRY: 'ENTER_PENCIL_ENTRY',
  ISSUE_NOTICE_135D: 'ISSUE_NOTICE_135D',
  FIELD_INSPECTION_RECORD: 'FIELD_INSPECTION_RECORD',
  SANCTION_MUTATION: 'SANCTION_MUTATION',
  REJECT_MUTATION: 'REJECT_MUTATION',
  HEAR_REVENUE_CASE: 'HEAR_REVENUE_CASE',
  APPROVE_SEC_36A_TRANSFER: 'APPROVE_SEC_36A_TRANSFER',

  // Administrative & Analytics
  VIEW_WORK_QUEUE: 'VIEW_WORK_QUEUE',
  VIEW_DISTRICT_ANALYTICS: 'VIEW_DISTRICT_ANALYTICS',
  VIEW_STATE_ANALYTICS: 'VIEW_STATE_ANALYTICS',
  VIEW_NATIONAL_METRICS: 'VIEW_NATIONAL_METRICS',
  MANAGE_INTEGRATIONS: 'MANAGE_INTEGRATIONS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_DATA_QUALITY_ANOMALIES: 'VIEW_DATA_QUALITY_ANOMALIES',
};

export const ROLE_PERMISSIONS = {
  [ROLES.CITIZEN]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.DOWNLOAD_DIGITAL_712,
    PERMISSIONS.APPLY_MUTATION,
    PERMISSIONS.VIEW_CITIZEN_PARCELS,
    PERMISSIONS.VIEW_WATCHLIST,
    PERMISSIONS.LODGE_GRIEVANCE,
  ],
  [ROLES.TALATHI]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.ENTER_PENCIL_ENTRY,
    PERMISSIONS.ISSUE_NOTICE_135D,
    PERMISSIONS.FIELD_INSPECTION_RECORD,
    PERMISSIONS.VIEW_WORK_QUEUE,
  ],
  [ROLES.PATWARI]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.ENTER_PENCIL_ENTRY,
    PERMISSIONS.FIELD_INSPECTION_RECORD,
    PERMISSIONS.VIEW_WORK_QUEUE,
  ],
  [ROLES.TEHSILDAR]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.SANCTION_MUTATION,
    PERMISSIONS.REJECT_MUTATION,
    PERMISSIONS.HEAR_REVENUE_CASE,
    PERMISSIONS.VIEW_WORK_QUEUE,
    PERMISSIONS.VIEW_DISTRICT_ANALYTICS,
    PERMISSIONS.VIEW_DATA_QUALITY_ANOMALIES,
  ],
  [ROLES.SRO]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.VIEW_WORK_QUEUE,
    PERMISSIONS.MANAGE_INTEGRATIONS,
  ],
  [ROLES.COLLECTOR]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.APPROVE_SEC_36A_TRANSFER,
    PERMISSIONS.HEAR_REVENUE_CASE,
    PERMISSIONS.VIEW_DISTRICT_ANALYTICS,
    PERMISSIONS.VIEW_STATE_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [ROLES.STATE_PMU]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.VIEW_STATE_ANALYTICS,
    PERMISSIONS.VIEW_DISTRICT_ANALYTICS,
    PERMISSIONS.VIEW_DATA_QUALITY_ANOMALIES,
    PERMISSIONS.MANAGE_INTEGRATIONS,
  ],
  [ROLES.NATIONAL_MONITOR]: [
    PERMISSIONS.VIEW_PUBLIC_RECORDS,
    PERMISSIONS.VIEW_NATIONAL_METRICS,
    PERMISSIONS.VIEW_STATE_ANALYTICS,
  ],
  [ROLES.ADMIN]: [
    ...Object.values(PERMISSIONS),
  ],
};

export const hasPermission = (userRole, permission) => {
  if (!userRole || !ROLE_PERMISSIONS[userRole]) return false;
  return ROLE_PERMISSIONS[userRole].includes(permission);
};

export default PERMISSIONS;
