/**
 * User roles in Land Stack platform
 */
export const ROLES = {
  CITIZEN: 'CITIZEN',
  TALATHI: 'TALATHI',
  PATWARI: 'PATWARI',
  TEHSILDAR: 'TEHSILDAR',
  CRO: 'CRO', // Circle Revenue Officer
  SURVEY_OFFICER: 'SURVEY_OFFICER',
  SURVEY_GIS: 'SURVEY_GIS',
  ULB_OFFICER: 'ULB_OFFICER',
  SRO: 'SRO', // Sub-Registrar Officer
  COLLECTOR: 'COLLECTOR',
  STATE_PMU: 'STATE_PMU',
  NATIONAL_MONITOR: 'NATIONAL_MONITOR',
  AUDITOR: 'AUDITOR',
  ADMIN: 'ADMIN',
};

export const ROLE_DEFINITIONS = [
  { id: ROLES.CITIZEN, name: 'Citizen / Landholder', portal: 'citizen', description: 'Access personal land records, 7/12, 8A, applications, and due diligence' },
  { id: ROLES.TALATHI, name: 'Talathi (Village Officer)', portal: 'government', description: 'Maintains village Form 6, 7/12, pencil entries, and field verifications' },
  { id: ROLES.PATWARI, name: 'Patwari / Revenue Inspector', portal: 'government', description: 'Village inspections, boundary verifications, and crop surveys' },
  { id: ROLES.TEHSILDAR, name: 'Tehsildar & Executive Magistrate', portal: 'government', description: 'Sanctions e-Ferfar mutations, hears quasi-judicial RTS revenue cases' },
  { id: ROLES.CRO, name: 'Circle Revenue Officer (CRO)', portal: 'government', description: 'Supervises circle patwaris and verifies contested revenue claims' },
  { id: ROLES.SURVEY_OFFICER, name: 'Cadastral Survey Officer', portal: 'government', description: 'Field surveys, ETS measurement, and cadastral demarcation' },
  { id: ROLES.SURVEY_GIS, name: 'GIS / Cadastral Cartographer', portal: 'government', description: 'Spatial parcel geometry validation, polygon topology, and drone layers' },
  { id: ROLES.ULB_OFFICER, name: 'Urban Local Body Officer', portal: 'government', description: 'Municipal property tax, building permissions, and urban CTS cards' },
  { id: ROLES.SRO, name: 'Sub-Registrar Officer (SRO)', portal: 'government', description: 'Registers conveyances, deeds, and synchronizes with Land Stack registry' },
  { id: ROLES.COLLECTOR, name: 'District Collector', portal: 'government', description: 'District administration, Section 36A permissions, and revenue vigilance' },
  { id: ROLES.STATE_PMU, name: 'State Project Management Unit (PMU)', portal: 'government', description: 'State-wide digitization monitoring, cadastral integrations, and SLAs' },
  { id: ROLES.NATIONAL_MONITOR, name: 'National Cadastral Monitor (DoLR)', portal: 'government', description: 'National land record modernization programme benchmarks and ULPIN metrics' },
  { id: ROLES.AUDITOR, name: 'Revenue & Vigilance Auditor', portal: 'government', description: 'Statutory compliance auditing and anti-fraud scrutiny' },
  { id: ROLES.ADMIN, name: 'System Administrator', portal: 'government', description: 'System configuration, role assignment, audit logs, and security controls' },
];

export const GOVERNMENT_ROLE_PRESETS = [
  {
    role: 'TALATHI',
    title: 'Talathi / Patwari',
    vernacular: 'तलाठी / पटवारी',
    designation: 'Village Revenue Officer',
    department: 'Revenue & Land Records',
    jurisdiction: 'Wagholi Circle, Haveli Tehsil, Pune',
    sampleOfficer: 'Prakash Shinde',
    icon: '👤',
    color: '#0b3c5d',
    badgeText: 'Field Verifications',
    route: '/government/talathi',
    description: 'Ground-level field inspections, Form 6 pencil entries, geotagged site photo capture, possession verification, and structured recommendations to Tehsildar.',
  },
  {
    role: 'TEHSILDAR',
    title: 'Tehsildar & Executive Magistrate',
    vernacular: 'तहसीलदार',
    designation: 'Primary Statutory Authority',
    department: 'Revenue & Land Records',
    jurisdiction: 'Haveli Taluka, Pune District',
    sampleOfficer: 'Sanjay Deshmukh',
    icon: '⚖️',
    color: '#dc2626',
    badgeText: 'Statutory Sanction',
    route: '/government/tehsildar',
    description: 'Statutory sanction or rejection of e-Ferfar mutation orders, RTS revenue court hearings, clarification directives, and AI risk advisory overrides.',
  },
  {
    role: 'SRO',
    title: 'Sub-Registrar Officer (SRO)',
    vernacular: 'दुय्यम निबंधक',
    designation: 'Registration Authority (Registration Act 1908)',
    department: 'Registration & Stamps',
    jurisdiction: 'Sub-Registrar Office Haveli No 5, Pune',
    sampleOfficer: 'Rekha Joshi',
    icon: '🏛️',
    color: '#7c3aed',
    badgeText: 'Deed Audits & NGDRS',
    route: '/government/registration',
    description: 'Pre-registration instant ULPIN title audit, encumbrance verification, court stay check, and NGDRS deed execution webhook synchronization.',
  },
  {
    role: 'COLLECTOR',
    title: 'District Collector & DM',
    vernacular: 'जिल्हाधिकारी',
    designation: 'District Administrative Authority',
    department: 'District Administration',
    jurisdiction: 'Pune District (14 Tehsils)',
    sampleOfficer: 'Dr. Suhas Diwase, IAS',
    icon: '🏢',
    color: '#0369a1',
    badgeText: 'District Cockpit',
    route: '/government/district',
    description: 'District command cockpit, 14 tehsils SLA compliance choropleth, inter-tehsil dispute escalations, Section 36A approvals, and officer reallocation.',
  },
  {
    role: 'ULB_OFFICER',
    title: 'Urban Local Body (ULB) Officer',
    vernacular: 'नागरी स्थानिक स्वराज्य संस्था अधिकारी',
    designation: 'Urban Land Records Officer',
    department: 'Municipal Administration & Revenue',
    jurisdiction: 'Pune Municipal Corporation (PMC)',
    sampleOfficer: 'Anita Bhosale',
    icon: '🏛️',
    color: '#1e3a8a',
    badgeText: 'Urban CTS & Planning',
    route: '/government/ulb',
    description: 'City Survey CTS property card management, PMRDA 2041 zoning & permissible FSI compliance, municipal property tax verification, and statutory urban mutation orders.',
  },
  {
    role: 'SURVEY_GIS',
    title: 'Cadastral Survey & GIS Specialist',
    vernacular: 'भूमापन व जीआयएस तज्ज्ञ',
    designation: 'Cadastral Cartographer',
    department: 'Directorate of Land Records',
    jurisdiction: 'Haveli Cadastral Division, Pune',
    sampleOfficer: 'Vikram Patole',
    icon: '🧭',
    color: '#0f766e',
    badgeText: 'Spatial Topology & CORS',
    route: '/government/survey',
    description: 'Spatial parcel geometry validation, polygon topology verification, boundary overlap analysis, and cadastral area reconciliation against Record of Rights.',
  },
  {
    role: 'STATE_PMU',
    title: 'State PMU Head',
    vernacular: 'राज्य प्रकल्प व्यवस्थापन',
    designation: 'State Cadastral Programme Director',
    department: 'Revenue & Forest Department',
    jurisdiction: 'State of Maharashtra (36 Districts)',
    sampleOfficer: 'Anil Verma',
    icon: '📊',
    color: '#059669',
    badgeText: 'State Analytics',
    route: '/government/state',
    description: 'State-wide digitization monitoring, cadastral integrations, SLA compliance tracking, and district performance rankings.',
  },
  {
    role: 'NATIONAL_MONITOR',
    title: 'National Cadastral Monitor (DoLR)',
    vernacular: 'राष्ट्रीय भू-अभिलेख निरीक्षक',
    designation: 'National Programme Lead',
    department: 'Department of Land Resources (DoLR)',
    jurisdiction: 'National (36 States & Union Territories)',
    sampleOfficer: 'Meera Sengupta',
    icon: '🇮🇳',
    color: '#b45309',
    badgeText: 'National Modernization',
    route: '/government/national',
    description: 'National land record modernization programme benchmarks, ULPIN generation index, inter-state federation metrics, and national progress maps.',
  },
  {
    role: 'ADMIN',
    title: 'System Administrator',
    vernacular: 'प्रणाली प्रशासक',
    designation: 'Platform & Security Administrator',
    department: 'National Informatics Centre (NIC)',
    jurisdiction: 'Platform-wide / National NIC Cloud',
    sampleOfficer: 'Manoj Tiwari',
    icon: '⚙️',
    color: '#475569',
    badgeText: 'System Health & Security',
    route: '/government/admin',
    description: 'System health monitoring, RBAC security audits, API sync queue management, automated failover controls, and security event logs.',
  },
];

export default ROLES;
