-- =====================================================================
-- LAND-STACK / BharatBhumi — Safe Cleanup Script for Temporary Test Data
-- Version: 2.0
--
-- SAFETY GUARANTEES:
-- 1. Strictly targets records with test identifiers ('TEST_%') or TEST_RUN_2026.
-- 2. Respects foreign-key dependency order (child records deleted before parents).
-- 3. NEVER executes unconditioned DELETE queries.
-- 4. Leaves all permanent production/reference data untouched.
-- =====================================================================

BEGIN;

-- 1. Audit Trail records generated by test runs
DELETE FROM audit_events 
WHERE actor_id LIKE 'TEST_%' 
   OR resource_id LIKE 'TEST_%'
   OR user_agent = 'Node.js Test Runner';

-- 2. Notifications created for test users
DELETE FROM notifications 
WHERE id LIKE 'TEST_%' 
   OR user_id LIKE 'TEST_%';

-- 3. Watchlist items created by test citizens
DELETE FROM watchlist 
WHERE id LIKE 'TEST_%' 
   OR citizen_id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

-- 4. Citizen Grievances
DELETE FROM grievances 
WHERE id LIKE 'TEST_%' 
   OR citizen_id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

-- 5. Certificates & User Documents
DELETE FROM documents 
WHERE id LIKE 'TEST_%' 
   OR user_id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

-- 6. SRO Audit Entries
DELETE FROM sro_audits 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

-- 7. Mutation Timelines
DELETE FROM mutation_timeline 
WHERE id LIKE 'TEST_%' 
   OR mutation_id LIKE 'TEST_%';

-- 8. Mutations
DELETE FROM mutations 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

-- 9. Citizen Applications
DELETE FROM applications 
WHERE id LIKE 'TEST_%' 
   OR citizen_id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

-- 10. Application Types (only test-specific types)
DELETE FROM application_types 
WHERE code LIKE 'TEST_%';

-- 11. Parcel Sub-Resources
DELETE FROM parcel_documents 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

DELETE FROM court_cases 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

DELETE FROM tax_records 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

DELETE FROM zoning 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

DELETE FROM restrictions 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

DELETE FROM encumbrances 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

DELETE FROM ownership_records 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

-- 12. Public Notices & News created during testing
DELETE FROM notices 
WHERE id LIKE 'TEST_%' 
   OR parcel_ulpin LIKE 'TEST_%';

DELETE FROM news 
WHERE id LIKE 'TEST_%';

DELETE FROM government_services 
WHERE id LIKE 'TEST_%';

-- 13. Test Parcels
DELETE FROM parcels 
WHERE ulpin LIKE 'TEST_%';

-- 14. Test Government Users & Test Citizens
DELETE FROM government_users 
WHERE id LIKE 'TEST_%';

DELETE FROM citizens 
WHERE id LIKE 'TEST_%';

-- 15. Clean Test Metadata Marker
DELETE FROM test_run_metadata 
WHERE test_run_id = 'TEST_RUN_2026';

COMMIT;

-- Verify that all test records are cleanly removed
SELECT 'CLEANUP_SUCCESS' AS result, COUNT(*) AS remaining_test_parcels 
FROM parcels 
WHERE ulpin LIKE 'TEST_%';
